# What is a Gemfile?
# A Gemfile is a file that contains a list of gems that are required by a Ruby program
# It is similar to a package.json file in Node.js
# Run: sudo gem bundle install
# Run: bundle

source 'https://rubygems.org'

gem 'os'
gem 'cpf_cnpj', '~> 0.2.1'